apiVersion: v1
kind: PersistentVolume
metadata:
  name: janitor-storage
  labels:
    baseChart: {{ template "base_chart" $ }} 
    release: {{ $.Release.Name }}
    {{- include "sstk_cronjob.business_labels" $ | indent 4 }}
  annotations:
    {{- include "sstk_cronjob.business_annotations" $ | indent 4 }}  
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: devops-janitor-store.kic-ops.shuttercloud.org
      share: /
    volumeHandle: devops-janitor-store.kic-ops.shuttercloud.org#/#devops-janitor-store
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "sstk_cronjob.business_annotations" $ | indent 4 }}  
  labels:
    baseChart: {{ template "base_chart" $ }} 
    release: {{ $.Release.Name }}
    {{- include "sstk_cronjob.business_labels" $ | indent 4 }}
  name: devops-janitor-slack-bot-token
  namespace: cloud-devops-devops-janitor
spec:
  data:
  - remoteRef:
      key: external-secret/devops-janitor/slack-bot-token
    secretKey: SLACK_CHANNEL_TOKEN
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: devops-janitor-slack-bot-token
    template:
      engineVersion: v2
      metadata:
        labels:
          velero.io/exclude-from-backup: "true"
