{{- range $cronjob := .Values.jobs }}
{{- if hasKey $cronjob "name" }}
  {{- $jobName := $cronjob.name }}
  {{- $jobFile := $.Files.Get (printf "janitor-jobs/%s" $jobName) | fromYaml }}
  {{- $cronjob := mergeOverwrite (deepCopy $jobFile) (deepCopy $cronjob) }}
  {{- if $cronjob.configMaps }}
  {{- range $configName,$config := $cronjob.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    baseChart: {{ template "base_chart" $ }}
    release: {{ $.Release.Name }}
    {{- include "sstk_cronjob.business_labels" $ | indent 4 }}
    {{- range $key, $value := $cronjob.labels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
  annotations:
    {{- include "sstk_cronjob.business_annotations" $ | indent 4 }}
    {{- range $key, $value := $cronjob.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
data:
{{- toYaml $config.data | nindent 2 }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}