{{- range $cronjob := .Values.jobs }}
{{- if hasKey $cronjob "name" }}
  {{- $jobName := $cronjob.name }}
  {{ $jobFile := $.Files.Get (printf "janitor-jobs/%s" $jobName) | fromYaml }}
  {{ $cronjob := mergeOverwrite (deepCopy $jobFile) (deepCopy $cronjob) }}
  {{- range $pvcName,$pvcData := $cronjob.persistentVolumeClaims }}
    {{- if or (not $pvcData.type) (eq $pvcData.type "ebs-csi") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $pvcName }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    baseChart: {{ template "base_chart" $ }} 
    release: {{ $.Release.Name }}
    {{- include "sstk_cronjob.business_labels" $ | indent 4 }}
    {{- range $key, $value := ($cronjob).labels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
  annotations:
    {{- include "sstk_cronjob.business_annotations" $ | indent 4 }}
    {{- range $key, $value := $cronjob.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
spec:
  storageClassName: "ebs-csi-sc"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $pvcData.volumeSize | default "1Gi" }}  
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}