{{- range $cronjob := .Values.jobs }}
{{- if hasKey $cronjob "name" }}
  {{- $jobName := $cronjob.name }}
  {{ $jobFile := $.Files.Get (printf "janitor-jobs/%s" $jobName) | fromYaml }}
  {{ $cronjob := mergeOverwrite (deepCopy $jobFile) (deepCopy $cronjob) }}
  {{- range $externalSecretName,$secretData := $cronjob.externalSecrets }}
---
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: {{ $externalSecretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    baseChart: {{ template "base_chart" $ }}
    release: {{ $.Release.Name }}
    {{- include "sstk_cronjob.business_labels" $ | indent 4 }}
    {{- range $key, $value := $cronjob.labels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
  annotations:
    {{- include "sstk_cronjob.business_annotations" $ | indent 4 }}
    {{- range $key, $value := $cronjob.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}  
spec:
  refreshInterval: {{ $secretData.refreshInterval | default "5m" | quote }}
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: {{ $secretData.targetName | default $externalSecretName }}
    creationPolicy: Owner
    template:
      metadata:
        labels:
          velero.io/exclude-from-backup: "true"
  {{- if ($secretData).data }}
  data:
  {{- range $data := $secretData.data }}
  - secretKey: {{ $data.key }}
    remoteRef:
      key: {{ $data.key }}
      {{- if $data.property }}
      property: {{ $data.property }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- if ($secretData).dataFrom }}
  dataFrom:
  {{- range $keyName,$dataFrom := $secretData.dataFrom }}
  - extract:
      key: {{ $keyName }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}