{{- range $cronjob := .Values.jobs }}
{{- if hasKey $cronjob "name" }}
  {{- $jobName := $cronjob.name }}
  {{ $jobFile := $.Files.Get (printf "janitor-jobs/%s" $jobName) | fromYaml }}
  {{ $cronjob := mergeOverwrite (deepCopy $jobFile) (deepCopy $cronjob) }}
  {{- if (not ( (($cronjob).serviceAccount).external  )) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if $cronjob.serviceAccount }}
  name: {{ $cronjob.serviceAccount.name }}
  {{- else }}
  name: {{ printf "cloud-devops-devops-janitor-%s" $cronjob.name }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    baseChart: {{ template "base_chart" $ }}
    {{- include "sstk_cronjob.business_labels" $ | indent 4 }}
    {{- range $key, $value := (($cronjob).serviceAccount).labels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
  annotations:
    {{- include "sstk_cronjob.base_role" $ | indent 4 }}
    {{- include "sstk_cronjob.business_annotations" $ | indent 4 }}
    {{- range $key, $value := (($cronjob).serviceAccount).annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
    {{- end }}
  {{- end }}
  {{- end }}
