{{- if or (not .Values.admin) (and .Values.admin (not .Values.admin.existingSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" $ }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "keycloak.labels" $ | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.admin.user | default "admin" | b64enc }}
  password: {{ include "keycloak.password" . }}
{{- end }}