{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.domain }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    group: {{ .Values.certificate.issuer.group }}
    kind: {{ .Values.certificate.issuer.kind }}
    name: {{ .Values.certificate.issuer.name }}
  dnsNames:
  - {{ .Values.certificate.domain }}
  {{- if .Values.certificate.additionalHosts -}}
  {{-   range .Values.certificate.additionalHosts }}
  - {{ . | quote }}
  {{-   end }}
  {{- end }}
{{- end }}
