{{- if and .Values.database.password (not .Values.database.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" $ }}-database
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "keycloak.labels" $ | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.database.username | default "keycloak" | b64enc }}
  password: {{ .Values.database.password | b64enc }}
{{- end }}