apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/keycloak/bin/kc.sh
          args:
            - start
            - --http-enabled=true
          {{- if .Values.ports.http }}
          {{- "- --http-port="{{ .Values.ports.http }} | nindent 12 }}
          {{- else }}
          {{- "- --http-port=8080 }}" | nindent 12}}
          {{- end }}
          {{- if .Values.ports.https }}
          {{- "- --https-port="{{ .Values.ports.https }} | nindent 12 }}
          {{- end }}
          env:
            - name: KC_CACHE
              value: "ispn"
            - name: KC_CACHE_STACK
              value: "kubernetes"
          {{- if .Values.health.enabled }}
            - name: KC_HEALTH_ENABLED
              value: "true"
          {{- end }}
          {{- if .Values.proxy.enabled }}
            - name: KC_PROXY
              value: {{ .Values.proxy.mode }}
          {{- end }}
          {{- with .Values.extraEnv }}
          {{- tpl . $ | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              protocol: TCP
            {{- if .Values.ports.http }}
              containerPort: {{ .Values.ports.http }}
            {{- else }}
              containerPort: 8080
            {{- end }}
            {{- if .Values.ports.https }}
            - name: https
              containerPort: {{ .Values.ports.https }}
              protocol: TCP
            {{- end }}
          {{- if .Values.health.enabled }}
          {{- with .Values.health.startupProbe }}
          startupProbe:
          {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- with .Values.health.livenessProbe }}
          livenessProbe:
          {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- with .Values.health.readinessProbe }}
          readinessProbe:
          {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
